# These options define the various properties of a model.
#
# They overwrite the default values which are listed in the definition of the Configuration class.
#
[config]
learning_rate = 0.0001 # "triple_decay"
zero_center_folder = "/home/saturn/capn/mppi033h/Data/zero_center_folder/"
train_logger_display = 250
train_logger_flush = -1
verbose_train = 1
verbose_val = 1
validate_interval = 2
shuffle_train = true